language: java

addons:
  sonarcloud:
    organization: "1809-spark-usf"
    
jobs:
  include:
    - stage: pre-build
      script: mvn clean
  
    - stage: test
      script: mvn test org.jacoco:jacoco-maven-plugin:prepare-agent
    
    - stage: build
      script: mvn package
      
    - stage: quality
      script: mvn sonar:sonar

